### ISSUE TITLE
Gender of the names

### ISSUE THREAD

**Issue by msdejong** [RoboCupAtHome/Montreal2018#1]
Just to clarify: is it possible the male names and female names have been switched?

**Comment by fabricejumel** [comment]
I had the same remark

**Comment by LoyVanBeek** [comment]
Yep, those look like the columns are swapped in https://github.com/RoboCupAtHome/Montreal2018/blob/master/Files/Names.pdf
@kyordhel ?

**Comment by kyordhel** [comment]
No idea when I closed this. Whatever.

Last time I checked, the lists were **not** switched (and this has nothing to do with 3d1495a).

@LoyVanBeek wasn't this repo supposed to be **private** until June 16?

**Comment by LoyVanBeek** [comment]
IIRC, someone asked to make it public so I did. Don't recall who asked though.

**Comment by kyordhel** [comment]
We should make it private again. Since not all teams are aware that some of the information has been published, this could lead to harsh discussion about giving advantages to some teams.

**Comment by LoyVanBeek** [comment]
Done, made private

**Comment by awesomebytes** [comment]
It's public now. Closing.
