### ISSUE TITLE
Corrections in questions

### ISSUE THREAD

**Issue by thetaleofnarutouzumaki** [RoboCupAtHome/Montreal2018#3]
https://github.com/RoboCupAtHome/Montreal2018/blob/master/Files/Questions.csv

- **I that** Justin Trudeau is very handsome
- what was the first computer **IN** pass
- Why is Elon Musk **is** worried about AI's impact on humanity

**Comment by LoyVanBeek** [comment]
Can you make a pull request with your suggested fixes? Thnx!

**Comment by thetaleofnarutouzumaki** [comment]
yeah.
