### ISSUE TITLE
Duplication of Information (predefined locations)

### ISSUE THREAD

**Issue by Slothologist** [RoboCupAtHome/Montreal2018#7]
https://github.com/RoboCupAtHome/Montreal2018/blob/master/Files/Categories.pdf

and

https://github.com/RoboCupAtHome/Montreal2018/blob/master/README.md

provide completely different information regarding the predefined location of objects. Which one should be used?

**Comment by samaleksandrov** [comment]
The ReadMe file, @airglow said that the Categories.pdf file will be removed :)

**Comment by raphaelmemmesheimer** [comment]
Japp, use the ones that are written in the `README.md`

**Comment by Slothologist** [comment]
Thanks guys :D
